### ISSUE TITLE
Automatically exclude [bot] users from the contributors

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/github-changelog-generator#102]
We may want to expand this to any user with the `[bot]` suffix and not just filter out `@dependabot[bot]`.

**Comment by wilkinsona** [comment]
The README should be updated as part of this: https://github.com/spring-io/github-changelog-generator?tab=readme-ov-file#excluding-contributors

**Comment by snicoll** [comment]
Yeah extending to any bot would be nice indeed.
