### ISSUE TITLE
Allow issue sort order to be specified

### ISSUE THREAD

**Issue by snicoll** [spring-io/github-changelog-generator#34]
While polishing the list of dependency upgrades for a release, I had to sort them to find related updates. 

I really think that ordering them is an improvement in our case as we use a standard issue title "Upgrade to <Library> <Version>". Projects that do not use such a standard pattern may not see it as an improvement so we may need to offer an option.

Note that we should probably order things without considering the case as some library names start with an upper case and others don't.

**Comment by LooTKinGz** [comment]
File update
