### ISSUE TITLE
Extend release notes with "Removal" and "Deprecations" section

### ISSUE THREAD

**Issue by dreis2211** [spring-io/github-changelog-generator#39]
Hi,

I was reading the release notes of Spring-Boot 2.3.0.RC1 this morning and was "missing" an issue in the list: https://github.com/spring-projects/spring-boot/issues/20991. I only noticed this because I reported the issue ;-)

I found out that this is because issues labeled with `task` are not part of the release notes. While I agree that not everything is relevant for release notes, this particular issue above removes functionality in which I - as a user - am very much interested in. The same applies to deprecations. (Personally, they are of more interest to me than documentation updates.)

I was wondering if it makes sense to create a new section "Removed" and "Deprecations" (with their respective labels).

Let me know what you think.
Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks for raising this, @dreis2211, and sorry for the omission from the release notes.

I think it was a mistake that spring-projects/spring-boot#20991 was labelled as a task. Tasks are intended to be pieces of work that should have no impact on users and 20991 doesn't fit that description. I've changed it to an enhancement and edited the release notes to add it.

Enhancements go in the New Features section. That's not a perfect fit for 20991 and we've struggled with similar issues recently. For example, https://github.com/spring-projects/spring-boot/issues/20823, deprecation of support for Bitronix, was labelled as a documentation issue as that seemed to be the least bad fit.

I like the idea of a new section or two to better categorise this sort of change. I think it might lead to some issues that belong in multiple categories. For example an issue that makes an enhancement could also deprecate something. https://github.com/spring-io/github-release-notes-generator/pull/38 will help with that but coming up with a title for the issue that makes sense in both categories will be a challenge.

**Comment by dreis2211** [comment]
No need to be sorry. Just to make things clear: I didn't care about the fact that it was **"my"** issue that wasn't listed. I was rather seeing this from the user perspective. If a user tries to find out why his properties stopped working, the release notes are one of the things I would personally check first.

**Comment by philwebb** [comment]
I'm going to move this one to Spring Boot under https://github.com/spring-projects/spring-boot/issues/23483.
