### ISSUE TITLE
Provide a way to link to release notes

### ISSUE THREAD

**Issue by philwebb** [spring-io/github-changelog-generator#46]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
The changelog generator does not have a way to add external links to it. For example, when a new version of Spring Boot is released, it is accompanied by [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes) on the Github Wiki. It would be nice if the changelog could point to these release notes so that they are easy to discover. 

## Solution
Add an option to add external links at the bottom of the changelog. These links should be configurable using a property as follows:

```yml
changelog:
  external_links:
  - name: Release notes
    location: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes
```
The content for the changelog is generated [here](https://github.com/spring-io/github-changelog-generator/blob/de36bf5646bd623368f7521e9878518f7694a183/src/main/java/io/spring/githubchangeloggenerator/ChangelogGenerator.java#L127). The tests for verifying the output can be found [here](https://github.com/spring-io/github-changelog-generator/blob/de36bf5646bd623368f7521e9878518f7694a183/src/test/java/io/spring/githubchangeloggenerator/ChangelogGeneratorTests.java).
```

## Steps to Fix 
 
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-io/github-changelog-generator/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by mahendrabishnoi2** [comment]
Hi @philwebb @mbhave I would like to work on this issue.

**Comment by jorgevasquezang** [comment]
Hi, I would like to work on this Issue

**Comment by mbhave** [comment]
@mahendrabishnoi2 Sure, it's all yours.

@jorgevasquezang Thank you but @mahendrabishnoi2  has already claimed this issue. Please keep an eye out for another first-timers-only issue and we’d be happy to guide you through the process then.

**Comment by jorgevasquezang** [comment]
Oh Sorry, didn't notice that, I will close my PR thanks!

**Comment by mbhave** [comment]
@mahendrabishnoi2 How is it going?

**Comment by mahendrabishnoi2** [comment]
@mbhave I'll complete the task on upcoming weekend

**Comment by mahendrabishnoi2** [comment]
@mbhave for these changes can I add myself as author or are these considered as cosmetic changes?

**Comment by snicoll** [comment]
Closing in favour of PR #55
