### ISSUE TITLE
Include body content

### ISSUE THREAD

**Issue by yceballost** [spring-io/github-changelog-generator#78]
Hi team, thanks a lot for the action!

I would like to know if its possible to add a little paragraph at the beginning of the changelog and then, the changelog structure.

Regards!

**Comment by wilkinsona** [comment]
It isn't possible at the moment. What sort of content would you like to be able to add?

**Comment by philwebb** [comment]
I'll close this one for now, but we're happy for consider a pull-request for such a feature.
