### ISSUE TITLE
Allow sections to only include issues or pull requests

### ISSUE THREAD

**Issue by steven-sheehy** [spring-io/github-changelog-generator#85]
## Problem

I target both issues and PRs to milestones, but I'd like to only include issues in the changelog. Having both in the changelog duplicates information and makes it harder to read. For Dependabot, there is no corresponding issue so I'd like include both or just PRs for the dependencies section.

## Solution

* Add a `changelog.sections[].type` enum property with values `ANY`, `ISSUE`, or `PULL_REQUEST`
* Default `type` property to `ANY` if not specified for backwards compatibility with existing configuration
* Filter sections based upon property to only contain the requested issue type

**Comment by wilkinsona** [comment]
>  Having both in the changelog duplicates information and makes it harder to read.

We avoid this problem by only having an issue or a pull request in a milestone for a particular change. In the spirit of that, I'll close this as superseded by #86.
