### ISSUE TITLE
Underscores should not be escaped when enclosed in back ticks

### ISSUE THREAD

**Issue by sbrannen** [spring-io/github-changelog-generator#87]
When the entry for https://github.com/spring-projects/spring-framework/issues/29799 was generated for the [Spring Framework 6.1.0-M4 release notes](https://github.com/spring-projects/spring-framework/releases), the underscores in `FactoryBean.OBJECT_TYPE_ATTRIBUTE` were unnecessarily escaped as follows.

> - Clarify `FactoryBean.OBJECT\_TYPE\_ATTRIBUTE` supported types [#29799](https://github.com/spring-projects/spring-framework/issues/29799)

**Comment by wilkinsona** [comment]
See gh-50 that introduced the escaping of Markdown styling characters.

**Comment by sbrannen** [comment]
Thanks, Andy! 👏
